apiVersion: v1
kind: Namespace
metadata:
  name: todo-m

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-m
              mountPath: /data/db
      volumes:
        - name: mongo-mi
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-m
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todo-m
  template:
    metadata:
      labels:
        app: todo-m
    spec:
      containers:
        - name: todo-m
          image: adamchouk23/appmicro:1.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: todo-m-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: todo-m
spec:
  selector:
    app: todo-m
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-m-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-m
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
